### PR TITLE
Desktop notifications

### PR DESCRIPTION
**Pull request by lelandjansen**
**Overview**
* Shows desktop notifications on command completion.
* Cross-platform (Linux, macOS, Windows).
* Provides `--no-desktop` CLI option.

**Warning**:  When no GUI is present, the program crashes on Linux (#32), hangs on macOS (#33), and returns an Error on Windows (#35).

**Testing**
* Manual tests on each platform (GUI environment).
* Warning: **NOT** unit tested.
* `did_it_run/src/notifications/desktop.rs` is omitted by code coverage.
* `--no-desktop` option passed to test scripts.

Tasks:
- [x] Notification dispatcher
- [x] Linux notifications
- [x] macOS notifications
- [x] Windows notifications

### CODE REVIEW

**Comment by hoodie** [comment]
BTW: there is [notify-rust](https://docs.rs/notify-rust/) which brings both a very idiomatic API and native linux and mac support. It actually uses mac-notification-sys itself

**Comment by lelandjansen** [comment]
> BTW: there is notify-rust which brings both a very idiomatic API and native linux and mac support. It actually uses mac-notification-sys itself

Thanks for the tip @hoodie! I explored using `notify-rust` earlier and did like the API, though ultimately decided to roll my own for a few reasons:
* I wanted more control over the underlying libraries on each platform. For example, `notify-rust` uses `dbus` on Linux whereas I found `libnotify` to be more portable.
* My code for desktop notifications on all three platforms is only ~200 lines (small burden for a major feature and avoids another dependency layer).
* I need to support Windows (and researched other cross-platform notification libraries but ultimately decided against them as well).

**Comment by hoodie** [comment]
Afaik libnotify also uses dbus, the notification API is a dbus interface. Plus libnotify depends on glib while notify-rust uses dbus directly

**Comment by lelandjansen** [comment]
> Afaik libnotify also uses dbus, the notification API is a dbus interface. Plus libnotify depends on glib 

Thanks for the tip @hoodie! I didn't know libnotify depends on dbus and you raise a good point about the glib dependency. In that case, it's probably worth switching libraries.

Issue: https://github.com/lelandjansen/did-it-run/issues/36

**Pull request merged**
